<?php 
session_start();
if(!isset($_SESSION['admin_name'])){
   header("Location:signin.php");
}
$admintitle = 'Approved Images';
include 'header.php';
include 'sidebar.php';
?>
<link rel="stylesheet" href="css/pagination.css"><script src="js/pagination.js"></script><div id="page-wrapper" class="gray-bg dashbard-1"><div class="content-main"><div class="banner"><h2><a href="./">Home</a><i class="fa fa-angle-right"></i><span>Approved Image</span><p class="pull-right" href="">5555 </p><b class="pull-right fa fa-angle-right">&nbsp</b><p class="pull-right" href="">Total</p></h2></div><div class="blank"><div class="blank-page"><table class="table table-bordered"><caption>Approved Images <a class="pull-right" href="" value="Refresh Page" onClick="refresh"><i class="fa fa-refresh" aria-hidden="true"></i></a></caption><thead><tr style=""><th>ID</th><th>Image Name</th><th>View</th><th>att</th><th>Keywords</th><th>Uploaded By</th><th>Process</th></tr></thead><tbody>
<?php $limit = 20;  if (isset($_GET["page"])) { $page  = $_GET["page"]; } else { $page=1; };  $start_from = ($page-1) * $limit;  $sql = "SELECT * FROM image WHERE approved=1 ORDER BY id DESC LIMIT $start_from, $limit";  $rs_result = mysqli_query($con, $sql); while ($row = mysqli_fetch_assoc($rs_result)) { ?><tr><td><?php echo $row['id']; ?></td><td><?php echo $row['iname']; ?></td><td><img src="../<?php echo $row['thumb'] ?>" height="30px" width="auto"></td><td><a href="../image?id=<?php echo $row['id']; ?>" target="_blank" >View</a></td><td><?php echo $row['itags']; ?></td><td><?php echo $row['image_by']; ?></td><td>           <!-- Action Button For Approved Unprroved or Delete Image --><a href="edit.php?id=<?php echo $row['id']; ?>"> <button type="button" class="btn btn-default dropdown-toggle" aria-haspopup="true" aria-expanded="false"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a></td></tr><?php  }  ?> </tbody></table><?php  $sql = "SELECT COUNT(id) FROM image";  $rs_result = mysqli_query($con, $sql);  $row = mysqli_fetch_row($rs_result);  $total_records = $row[0];  $total_pages = ceil($total_records / $limit);  $pagLink = "<nav style='margin-top: 10px;'><ul class='pagination'>";  for ($i=1; $i<=$total_pages; $i++) {  $pagLink .= "<li><a href='index?page=".$i."'>".$i."</a></li>";  } echo $pagLink . "</ul></nav>";  ?></div></div>
<style> .pagination>li>a:focus,.pagination>li>a:hover,.pagination>li>span:focus,.pagination>li>span:hover{z-index:2;color:#000;background-color:#eee;border-color:#a4a4a4}.pagination>li>a,.pagination>li>span{position:relative;float:left;padding:6px 12px;margin-left:-1px;line-height:1.42857143;color:#666;text-decoration:none;background-color:#fff;border:1px solid #ddd}.pagination>.active>a,.pagination>.active>a:focus,.pagination>.active>a:hover,.pagination>.active>span,.pagination>.active>span:focus,.pagination>.active>span:hover{z-index:3;color:#fff;cursor:default;background-color:#777;border-color:#777} </style>
<script type="text/javascript">$(document).ready(function(){$('.pagination').pagination({items:<?php echo $total_records;?>,itemsOnPage:<?php echo $limit;?>,cssStyle:'light-theme',currentPage:<?php echo $page;?>,hrefTextPrefix:'image?page='});});</script><?php include 'footer.php'; ?>